### ISSUE TITLE
Unary relationship

### ISSUE THREAD

**Issue by askalyan** [rterrabh/TerraER#17]
A unary relationship in terraer can not be connected properly. both the line of an entity with the relatioship are overlapping and seen as oneline

**Comment by askalyan** [comment]
descriptive attributes connected  to the relationship are seen in red line which a bit confusing.

**Comment by obedecarvalho** [comment]
Thanks for your comments we will be evaluating them. Regarding the second comment, the error in the evaluation of a link between a relationship and an attribute has already been corrected, and will be available in the next version.

**Comment by rterrabh** [comment]
Yes, the second comment has been already fixed by @obedecarvalho.

And regarding the first one, if you double click over the line, it allows you to manually change the position. Check it out at: https://github.com/rterrabh/TerraER/blob/master/terraer-example01.mp4

In a nutshell:
1. It can be done manually, but we will find a way to automatically do that (this happens a lot with several users and we need to avoid that).
2. Done for the next release.
