### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jadesoturi** [rterrabh/TerraER#6]
Hello.

Thanks for an awesome tool! 

What I have really isn't an issue, but more of a request/question.

I'm taking Database Systems this semester, and we are just starting with ER modelling. I found your tool very useful, but I have a questions: when connecting an partial_key attribute to an entity, the line is always red. If I go into the Edit menu and select Validate Model - it turns normal/black. Why is this? What is the difference between Validate Model and validateModel2 options. Could you provide some documentation?

Also, what is the difference between  EntityRelationship and regular Relationship?

Thank you in advance.

Best Regards
//jadesoturi

**Comment by rterrabh** [comment]
Hi Jadesoturi. As you yourself mention, this is not an issue. So, I'm closing it. I kindly ask you to contact me by email (rterrabh@gmail.com).

Some answers:
- "Partial Key" can be connect only with "Weak Entity".
- I did not understand the Validate Model and validateModel2 options? Perhaps, it is a bug. Could you describe better this (with screenshots, for instance)? Which release are you using? I strongly recommend the last one (TerraER2.23). In theory, there is "Disable Model Checking" label when model checking is active and "Enable Model Checking" label otherwise.
- When there is a relationship between two entities and such relationship generates attributes, this is the case of an entityrelationship. I have a good tutorial (but in portuguese), you can ask me by email as well.

Best, R. Terra
